name: connecta_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  # Packages
  riverpod: ^2.3.6
  flutter_riverpod: ^2.3.6
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  go_router: ^8.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  stack_trace: ^1.11.0
  intl: ^0.18.0

  # Firebase
  firebase_core: ^2.13.1
  firebase_analytics: ^10.4.2
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.1

  # UI
  cupertino_icons: ^1.0.2
  animate_do: ^3.0.2
  
  # Debug
  logger: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Packages
  flutter_lints: ^2.0.0
  build_runner: ^2.4.5
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  hive_generator: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/i18n/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
